language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.7"  # not supported on travis

addons:
  apt:
    packages:
    - gfortran
    - libatlas-dev
    - libevent-dev
    - libfreetype6-dev
    - liblapack-dev
    - libpng12-dev
    - python-dev
    - python-tk

install:
  - pip -qqq install --upgrade pip setuptools
  - pip install tox-travis

cache:
  apt: false
  directories:
    - /home/travis/virtualenv/python2.7_with_system_site_packages/lib/python2.7

script: tox

notifications:
  email: false
